### ISSUE TITLE
Help required for changing font

### ISSUE THREAD

**Issue by toymaker7** [Tropix126/BetterDiscordStuff#10]
Is changing font Universally doable? I want the Ubuntu font all over the discord. How can i do it?

**Comment by Tropix126** [comment]
Yes. Put this at the **TOP LINE** of your custom css menu.

```
@import url('https://fonts.googleapis.com/css?family=Ubuntu');
#app-mount {font-family:'Ubuntu' !important;}```

**Comment by toymaker7** [comment]
yep, its working. Thanks!
I was going around adding font-family attributes in every part of the base.css i forked.
