### ISSUE TITLE
Aurora - BetterDocs - [Issue Report]

### ISSUE THREAD

**Issue by SwagXD** [Tropix126/BetterDiscordStuff#11]
So yesterday i installed the theme, it was working fine, but suddenly today all the icons seems to be uh changed, like this.
![Screenshot (27)](https://user-images.githubusercontent.com/49137868/55302044-a2bb6480-5469-11e9-8420-da7faf54df1a.png)

**Comment by twitchcord** [comment]
Yes, this is due to an image optimization feature pushed recently.

**Comment by SwagXD** [comment]
okay

**Comment by SwagXD** [comment]
i just realized its april fool

**Comment by Tropix126** [comment]
kapp

**Comment by Tropix126** [comment]
Also do not use betterdocs to download themes. It posts creators content without their permission and is generally a bad source.
