### ISSUE TITLE
Aurora - BetterDocs - [YOUR THEME IS BROKEN]

### ISSUE THREAD

**Issue by XAcidX** [Tropix126/BetterDiscordStuff#12]
![image](https://user-images.githubusercontent.com/48640901/55306503-c3f06680-5411-11e9-9521-080bdb7a6ea5.png)

**Comment by Nova4Dayz** [comment]
i got that also it just did a update and then it looked like that i was like wtf

**Comment by JustinADavidson** [comment]
have you guys not heard of April Fools lol

**Comment by Tropix126** [comment]
April fools, also do not use betterdocs. They posted my theme there without my consent and do not show any respect for people who want it removed. it also contains plugins that could get you banned.
