### ISSUE TITLE
Aurora - BetterDocs - [Issue Report]

### ISSUE THREAD

**Issue by tfwraxQQ** [Tropix126/BetterDiscordStuff#13]
I cant remove the default avatar icon

**Comment by JustinADavidson** [comment]
It's a April Fools thing it will be removed after its over

**Comment by Tropix126** [comment]
Removed the april fools, also do not use betterdocs to download themes and plugins. They posted my stuff there without any asking for permission and have had no respect for me asking it to be taken down. They also have plugins that could get your account banned from discord. (message loggers, account switchers etc...)
