### ISSUE TITLE
The april fools thing is stupid.

### ISSUE THREAD

**Issue by NateKomodo** [Tropix126/BetterDiscordStuff#16]
Seriously, i just want to use discord. Leave me alone.

In what world is ruining an entire theme a good idea.

**Comment by JustinADavidson** [comment]
as Patrick would say "take it easy its just a drawing"

**Comment by NateKomodo** [comment]
It makes the theme completely unusable though, and theres no way to be rid of it without changing themes

**Comment by Tropix126** [comment]
Removing it now.
