### ISSUE TITLE
Aurora - BetterDocs - [Issue Report]

### ISSUE THREAD

**Issue by gotenplays151** [Tropix126/BetterDiscordStuff#17]
da faces

**Comment by Tropix126** [comment]
April foold kappa

**Comment by Tropix126** [comment]
Also, do not use betterdocs, since it looks like you came from there. Betterdocs is an unofficial source that posts creators themes there without permission and has no respect for them when they ask for a removal. Only download from the betterdiscord server repositories.

**Comment by gotenplays151** [comment]
Got It, imma stop using it

Em seg, 1 de abr de 2019 17:35, Tropical <notifications@github.com>
escreveu:
