### ISSUE TITLE
Add option to add custom background

### ISSUE THREAD

**Issue by squadramunter** [Tropix126/BetterDiscordStuff#2]
Please describe on the README page how to add your custom background to fit your needs.

First I would say that I like the layout but I want my own custom background in place. In the CSS file I can see that the base.css is imported from your side.

Is there a way to overwrite the background in the Custom CSS Editor from BetterDiscord built-in?

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/53293582-f87e5c00-379b-11e9-8b12-6d864614f699.png)
Yes, just edit these two values from the theme file. The links must be HTTPS, and you have to blur the background yourself with something like photoshop or gimp, or you can use some online blur tool like this : https://www298.lunapic.com/editor/?action=blur I recommend that the blurred background should also be darker. If you have further questions, mention me in the BetterDiscord server.
