### ISSUE TITLE
Aurora - BetterDocs - [Issue Report]

### ISSUE THREAD

**Issue by Huarech** [Tropix126/BetterDiscordStuff#20]
Dear Tropix126,

I've found a bug in the theme and that is this one.
http://prntscr.com/n631hb i just started up discord and i saw this, i dont know how it happend but yeah as you can see there is something not good

Greatz - Huarech

**Comment by Tropix126** [comment]
Lmao its april fools, also do not use betterdocs, it posts people stuff there without their permission and doesnt have respect for theme devs. I never asked my stuff to be posted there and you might find malicions plugins.

**Comment by Huarech** [comment]
Alright well what website is thrusted if BettDocs isn’t thrusted?


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Tropical <notifications@github.com>
Verzonden: Monday, April 1, 2019 10:34:25 PM
Aan: Tropix126/BetterDiscordStuff
CC: Huarech; Author
Onderwerp: Re: [Tropix126/BetterDiscordStuff] Aurora - BetterDocs - [Issue Report] (#20)


Lmao its april fools, also do not use betterdocs, it posts people stuff there without their permission and doesnt have respect for theme devs. I never asked my stuff to be posted there and you might find malicions plugins.

**Comment by Tropix126** [comment]
Use the betterdiscord servers, they are the only trusted source of themes and plugins.

**Comment by Tropix126** [comment]
Visit the #plugin repo and #theme repo channels to download.
