### ISSUE TITLE
Aurora - BetterDocs - [Issue Report]

### ISSUE THREAD

**Issue by Kimaul37** [Tropix126/BetterDiscordStuff#23]
There's a bug with the display of the theme on some parts of Discord like on images (not exhaustive). I use the last version of Canary. There is also visual bugs like in the #9 post. One can be seen with the logo of Discord in the right-hand corner on my first screenshot.
![Annotation 2](https://user-images.githubusercontent.com/28737149/56449590-d9bfc000-631b-11e9-915a-b7114d7f8403.png)
![Annotation](https://user-images.githubusercontent.com/28737149/56449591-d9bfc000-631b-11e9-82ca-875234ad08da.png)

**Comment by Tropix126** [comment]
Discord fucked everything. They did a complete UI overhaul and updated all the classes. It's gonna be weeks or even months before everything will be fixed and will probably need to rewrite the theme. This goes for most themes in the next few days. Also do not user BetterDocs, it profits off of my themes and refuses to get my theme off their site, as well as dealing potential harmful plugins.
