### ISSUE TITLE
Fonts and images no longer displaying properly

### ISSUE THREAD

**Issue by NateKomodo** [Tropix126/BetterDiscordStuff#25]
As of today the fonts and online status are not being displayed correctly, as seen below

![image](https://user-images.githubusercontent.com/31631620/56471624-8b5e0e80-644c-11e9-9120-bc0103396542.png)

**Comment by Tropix126** [comment]
it should be fixed now

**Comment by NateKomodo** [comment]
fonts are, but masks/shape is not
