### ISSUE TITLE
Visual Issues after update (Aurora)

### ISSUE THREAD

**Issue by MoriyaFaith** [Tropix126/BetterDiscordStuff#27]
Didn't know if this was an issue with BD, but it seems that multiple elements aren't displaying properly. Here's an example.
![image](https://user-images.githubusercontent.com/46070717/56697563-f6158100-66bc-11e9-8bb5-3729d274636d.png)

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/56698342-32de7980-66b7-11e9-8907-0d4ddbe60cea.png)
