### ISSUE TITLE
Citador bug

### ISSUE THREAD

**Issue by Cr0c81** [Tropix126/BetterDiscordStuff#28]
https://yadi.sk/i/o_YIw8icBhfReQ
After click citate popup at text input is hided

**Comment by Tropix126** [comment]
i dont even support citador yet

**Comment by Cr0c81** [comment]
https://yadi.sk/i/99spDcdRIQiH9w
In default theme is worked

**Comment by Tropix126** [comment]
Yes i know, I don't support citador on aurora.
