### ISSUE TITLE
Variable feature request

### ISSUE THREAD

**Issue by biscuut** [Tropix126/BetterDiscordStuff#32]
First of all I just want to say that this is an excellent theme, and thanks for spending your time on it.
I simply just have a feature request: is it possible to get a variable for disabling the expanding of the sidebar when you hover over it?

Don't get me wrong, it looks very clean and it has a great animation- but I find it really hard to to click the search, mute, deafen, and user settings bottom at the bottom left. For example, I aim my cursor towards the user settings button, but when I get close to the button they all move to the right, and it really throws me off and I press the mute button/miss my click completely.

Again, thanks, and I hope you consider this addition.

**Comment by Tropix126** [comment]
check aurora/addons/disableExpansions.css
