### ISSUE TITLE
Mobile Indicator Missing From Member List

### ISSUE THREAD

**Issue by KasKatto** [Tropix126/BetterDiscordStuff#35]
When another user is using the discord on mobile the indicator is missing from server member lists. The indicator is there when you click to view the user (see screenshot)
![image](https://user-images.githubusercontent.com/48245049/57545239-a0460780-7351-11e9-8ea3-14172a8a2a65.png)

(Applies to aurora theme)

**Comment by Sydnxt** [comment]
This is a discord update. Turn the theme off.

**Comment by KasKatto** [comment]
Oh indeed it is, i apologize. I haven't noticed this.

**Comment by Sydnxt** [comment]
All good, sucks though. It's a terrible change IMO
