### ISSUE TITLE
Dots and fonts

### ISSUE THREAD

**Issue by fr3dde** [Tropix126/BetterDiscordStuff#37]
Hello Tropix,

This is probably not an actual issue but a matter of preference and only subjective.

Dots on profile pictures that makes it hard to see what the actual picture is.
Proof : https://prnt.sc/nrd9rr

The font of my own name at the bottom.
Proof: https://prnt.sc/nrda0g

This one is probably just the same front as you used for the whole Aurora theme idea so i get it, but a clear font would be prefered.

I get that I can probably change all of this on my own but I am a total noob when it comes to CSS.

Love your theme none the less.

**Comment by Tropix126** [comment]
Turn off colorblind mode. (Settings > Appearance).
