### ISSUE TITLE
"quality theme": broken dependency

### ISSUE THREAD

**Issue by mbpscruise** [Tropix126/BetterDiscordStuff#38]
This issue concerns this file: https://github.com/Tropix126/BetterDiscordStuff/blob/master/bestthemeever/quality_theme.theme.css

The theme file tries to import "https://tropix126.github.io/BetterDiscordStuff/bestthemeever/index.css", which returns a 404 error.

**Comment by mbpscruise** [comment]
Obviously the file was set up like this for auto updating from GitHub, but the original source was deleted. Therefore it is misleading to include this folder.

**Comment by Tropix126** [comment]
The theme is fixed, sorry about this issue.
