### ISSUE TITLE
Spoilers on Aurora should probably have more blur

### ISSUE THREAD

**Issue by zaneneuschuler** [Tropix126/BetterDiscordStuff#4]
Title, I suppose. Right now I feel like the blur on the spoilers could bumped up a couple px as to obscure the contents of the spoiler a bit better.

 How the blur is currently: ![Blur right now](https://zaneis.moe/ss/2019-02-27_19-43_7464.png) 
(text says "Spoiler text as it is now")
 How it would look with 5px blur instead of 3px:  ![Blur with 5px](https://zaneis.moe/ss/2019-02-27_19-46_7465.png) 
(text says "Spoiler text with 5px")

Sorry for not formatting this better.

**Comment by Tropix126** [comment]
one sec

**Comment by Tropix126** [comment]
Updated, i cant really test it rn, but it should work now. If you have another issue with spoilers let me know 👍

**Comment by zaneneuschuler** [comment]
Looks great, thanks!
