### ISSUE TITLE
Midnight Theme - "This theme is called midnight, which implies that it's a dark theme."

### ISSUE THREAD

**Issue by SirMoreira** [Tropix126/BetterDiscordStuff#45]
![image](https://user-images.githubusercontent.com/49536383/60337794-69b46280-997a-11e9-9e65-bc2ef042fbc6.png)
I can't leave this message :/

**Comment by Tropix126** [comment]
Oh, my bad. Seems like discord updated the classes. Give me one second then press Ctrl + R  (not quite yet)
