### ISSUE TITLE
Unable to see unread message indicator on Midnight Theme

### ISSUE THREAD

**Issue by Infinidoge** [Tropix126/BetterDiscordStuff#46]
When using the midnight theme all servers, regardless of they have unread messages or not, have the unread message indicator tab
![image](https://user-images.githubusercontent.com/22727114/60744385-b0d6c080-9f43-11e9-9162-f94463f4c5c0.png)
(None of the above servers have unread messages)

If this is intended behavior, then what is the unread indicator icon? I can't tell any difference.

**Comment by agent31750** [comment]
Can't reproduce

![image](https://user-images.githubusercontent.com/29772841/60745690-bc45de00-9f7b-11e9-85f2-cf65d7e72a35.png)

**Comment by Infinidoge** [comment]
Huh, very weird. I'll go through and check if other plugins or theme addons are causing it.

**Comment by Infinidoge** [comment]
Found the culprit of sorts. ServerFolders moves all of the servers to the right which shows the whole indicator for some reason.
Is there any reason why this would occur with ServerFolders?

**Comment by Tropix126** [comment]
Use discord's native serverfolders. Could not reproduce bug.
