### ISSUE TITLE
z-index issue with Midnight

### ISSUE THREAD

**Issue by FrecklesTheTrashBunny** [Tropix126/BetterDiscordStuff#47]
When you're going to upload, or opening an image from chat, the opacity makes it too dark to see clearly, and unable to click the "upload" button. 
![image](https://user-images.githubusercontent.com/52782238/61041456-f1956600-a397-11e9-9617-17e45fa0a213.png) before 
![image](https://user-images.githubusercontent.com/52782238/61041472-fbb76480-a397-11e9-8e45-cc5902cf9027.png) after. 

Edit: It's any kind of popup,  like sending photos, opening photos, opening profiles turning the screen dark and unable to be read/interacted with like clicking send/cancel etc

**Comment by FrecklesTheTrashBunny** [comment]
Found the culprit. .backdrop-1wrmKB, .modal-1UGdnR { z-index: 1500 !important;} if you change that to 1000 or less it fixes it, but when you go to 1001 or above it breaks.

**Comment by Tropix126** [comment]
Fixed.
