### ISSUE TITLE
Text Color

### ISSUE THREAD

**Issue by masterhc** [Tropix126/BetterDiscordStuff#5]
I'm sorry if I'm just too stupid to figure this out on my own.
I would like to know where is it that you configured the text color used on the channel's name and the  user names inside the channels.
Anf if what I said isn't clear, as my english is far from perfect. I'm leaving this pic here.
![coiso](https://user-images.githubusercontent.com/20691313/53645684-580fb800-3c31-11e9-9591-0682c444257f.png)

While I'm am at it I have another thing to ask.
![image](https://user-images.githubusercontent.com/20691313/53645742-75448680-3c31-11e9-8ece-a0a3f8bbe425.png)

Is this my fault, or is there something you need to update?

Thx in advance, the theme you made is really good.

**Comment by Tropix126** [comment]
Set a backdropblurred variable. If you want it to be transparent and not blurred, just paste the same image link in for both variables.

**Comment by Tropix126** [comment]
The text color looks better when blurred, and that's why it looks strange in your case. I could convert them to factors of white later.
