### ISSUE TITLE
Aurora - Online status issue

### ISSUE THREAD

**Issue by derMiepz** [Tropix126/BetterDiscordStuff#50]
Seems like Discord updated some stuff regarding the online status. Now it's completely borked see: 
![image](https://user-images.githubusercontent.com/45405525/61581055-2c766700-ab19-11e9-8cd0-d78b1c12daf0.png)

**Comment by Tropix126** [comment]
aurora has been discontinued. Please use https://betterdiscord.net/ghdl?id=2917 instead :)
