### ISSUE TITLE
Aurora - Profile pictures have a straight line (shadow) next to them

### ISSUE THREAD

**Issue by derMiepz** [Tropix126/BetterDiscordStuff#51]
Title says it all: 
![image](https://user-images.githubusercontent.com/45405525/61581079-cb9b5e80-ab19-11e9-8543-faec19f18c54.png)

**Comment by SkytAsul** [comment]
Up!

**Comment by lls0308abc** [comment]
Here you can sovle it:
```
[class*="avatar-"], .image-33JSyf {
	box-shadow: none !important;
}
```

**Comment by SkytAsul** [comment]
> Here you can sovle it:
> 
> ```
> [class*="avatar-"], .image-33JSyf {
> 	box-shadow: none !important;
> }
> ```

Where should we put this? I don't know CSS

**Comment by lls0308abc** [comment]
base.css Line 358 (Section 3.a. Messages and Codeblocks)
![image](https://user-images.githubusercontent.com/21107283/62471833-12eb4580-b7d0-11e9-9bba-97f7f2c15869.png)

**Comment by SkytAsul** [comment]
OK so it works by putting this code in the live CSS Editor.
