### ISSUE TITLE
Midnight theme text box breaks with a extended sentence 

### ISSUE THREAD

**Issue by PepiBun** [Tropix126/BetterDiscordStuff#52]
![example](https://user-images.githubusercontent.com/54043247/62901599-9a3a3b00-bd33-11e9-85fe-a8455f6090ff.png)
![example2](https://user-images.githubusercontent.com/54043247/62901600-9a3a3b00-bd33-11e9-8d1e-4fc814d73d01.png)

It happens in any size I put discord in too.

**Comment by Tropix126** [comment]
Aware of this, will be adressed in future updates
