### ISSUE TITLE
Off-sync

### ISSUE THREAD

**Issue by lucotas82** [Tropix126/BetterDiscordStuff#6]
The ring around the player pfp gets off-sync.
https://cdn.discordapp.com/attachments/536554187429904394/551139163395850250/unknown.png

**Comment by Tropix126** [comment]
Im not bothering fixing stuff like 1px offsets. Switch your zoom level, as it works on 100% zoom. Stuff like this is impossible to fix on other text scaling/zoom levels without messing with other zoom levels. Welcome to css.
