### ISSUE TITLE
[Midnight] Improvements

### ISSUE THREAD

**Issue by Hampusm** [Tropix126/BetterDiscordStuff#64]
I've made a couple of aesthetic changes to Midnight that i personally think greatly improves the theme. You can find it [here](https://github.com/Hampusm/Midnight-Discord)

Here's a list of the differences:
* Title says Discord and not Midnight
* Removed the stupid "Thank you for using Midnight" message
* Your username and usertag in the user panel is centered
* Activity title is further away from activity icon
* Your email adress isn't blurred
* Account panel background is transparent
* Account panel buttons aren't actual buttons
* Message input box background is transparent.

It's, of course, ok if you disapprove of these changes as it is a separate repository and I can just continue on it myself. But I just thought that you would maybe at least be a little bit interested in these improvements and would take some inspiration.

**Comment by Tropix126** [comment]
I will take consideration these, however many are intentional. It's perfectly fine to maintain a fork in a seperate repo though.
