### ISSUE TITLE
Incorrect display of a window with smilies

### ISSUE THREAD

**Issue by SeishinShinso** [Tropix126/BetterDiscordStuff#65]
I noticed that the window where emojis are not displayed correctly. The last column with emoji on the right is not displayed. How to fix? This problem applies to all emojis.
![Screenshot_3](https://user-images.githubusercontent.com/49783015/70919728-08687480-202a-11ea-843a-869ee09d23c7.png)
![Screenshot_4](https://user-images.githubusercontent.com/49783015/70919729-08687480-202a-11ea-80db-9f05d58fa02f.png)

**Comment by Tropix126** [comment]
just pushed a fix, let me know if there are stil issues 👍
