### ISSUE TITLE
Midnight UI: Grey area on friends tab

### ISSUE THREAD

**Issue by rojnwa** [Tropix126/BetterDiscordStuff#74]
I'm getting some weird grey area on the friends tab (probably the default grey).
There is also some glitchy behavior besides the settings button (bottom left).

Disabling all plugins does not resolve the problem. 

Stable 54270 (b7c8b43)
Host 0.0.305
Windows 10 64-Bit (10.0.18362)
BandagedBD 0.2.23 By Zerebos
Midnight UI V2.8.1 By Tropical

![Discord_2020-02-11_20-28-49](https://user-images.githubusercontent.com/19150352/74271466-3c4fd580-4d0d-11ea-9456-151a267d28e6.png)

**Comment by PetertheGray** [comment]
Same issue, seen this with other themes too. No settings issue for me, however. Some working ones are Black Hole, Discord Dark, Frosted Glass, etc. 
My specs:
Stable 55393 (b3019e6edd977edf02693cb7c10a3b8edf813583)
Host 0.0.306
Windows 8.1 Update 64-Bit (not sure where to check what version but I know its the latest so)
BandagedBD (also don't know version check but latest as of March 3rd)
Midnight UI V2.8.1 (just updated from the source theme file)
