### ISSUE TITLE
Aurora visual bugs

### ISSUE THREAD

**Issue by ghost** [Tropix126/BetterDiscordStuff#9]
The spotify listening menu is visually broken

![](https://i.imgur.com/Rq2o96f.png)

Also, on user profiles, this happens:
https://i.gyazo.com/4285e3371d43bde48d918c1affe74e5b.mp4

**Comment by Tropix126** [comment]
That is really strange, as it looks like not all of the CSS is applying to your user popout. Either way, ill look into it.

**Comment by galaxy119** [comment]
This is also affecting several other areas of the Discord client..
![Selection_818](https://user-images.githubusercontent.com/10914157/56711474-d9d70b80-66df-11e9-96bc-ac6c43bfb7cb.png)
![Selection_819](https://user-images.githubusercontent.com/10914157/56711475-d9d70b80-66df-11e9-8130-b7b9a9a5056d.png)
![Selection_820](https://user-images.githubusercontent.com/10914157/56711476-d9d70b80-66df-11e9-926a-9238b17bd0a5.png)
![Selection_821](https://user-images.githubusercontent.com/10914157/56711477-d9d70b80-66df-11e9-88b8-c7791a8f00f6.png)

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/56766548-49e0a280-676f-11e9-9352-df415b5fd9dc.png)
